name: To deploy Strapi app (Code Deploy)

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-2'
      TF_VERSION: '1.0.0'
      TF_WORKING_DIR: 'terraform/deploy/'

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Initialize Terraform'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: 'Terraform Format Check'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform fmt -check || true

    - name: 'Terraform Validate'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan

    - name: 'Terraform Apply'
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -auto-approve
